
c               Copyright 1993 Colorado State University
c                       All Rights Reserved


      common/fertil/aufert, feramt(3), gfertot(3), girrtot, gomadtot,
     &              gomaetot(3), ninhib, ninhtm,
     &              Nscalar(12), nreduce, OMADscalar(12)
      real aufert, feramt, gfertot, girrtot, gomadtot, gomaetot,
     &     ninhib, Nscalar, nreduce, OMADscalar
      integer ninhtm

      save/fertil/
